apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: am-node02
  namespace: monitoring
  labels:
    app: am-node02
spec:
  serviceName: am-service-02
  replicas: 1
  template:
    metadata:
      name: am-node02
      labels:
        app: am-node02
        run: alertmanager
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
            {
                "name": "check-am01",
                "image": "go-nexus:5000/prom/busybox:20170703",
                "command": ["sh", "-c", "until ping am-node01-0.am-service-01 -c 1; do sleep 3; done;"]
            }
        ]'
    spec:
      imagePullSecrets:
        - name: go-nexus
      containers:
      - name: am-node02
        image: go-nexus:5000/prom/alertmanager:v0.7.1
        #image: prom/alertmanager:v0.6.2
        args:
          - '-config.file=/etc/prometheus/alertmanager.conf'
          - '-mesh.peer-id=00:00:00:00:00:02'
          - '-mesh.nickname=am-node02'
          - '-mesh.listen-address=:8001'
          - '-mesh.peer=am-node01-0.am-service-01:8001'
          - '-log.level=debug'
        ports:
        - name: webport
          containerPort: 9093
        - name: peerport
          containerPort: 8001
        resources:
          requests:
            cpu: 500m
            memory: 500M
          limits:
            cpu: 500m
            memory: 500M
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        env:
        - name: TZ
          value: Asia/Chongqing

      volumes:
      - name: config-volume
        configMap:
          name: alertmanager-conf
      nodeSelector:
        app: prometheus

---

apiVersion: v1
kind: Service
metadata:
  name: am-service-02
  namespace: monitoring
  labels:
    app: am-node02
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9093'
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9093
      protocol: TCP
      name: webport
      targetPort: 9093
    - port: 8001
      protocol: TCP
      name: peerport
      targetPort: 8001
  selector:
    app: am-node02
