apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
spec:
  type: NodePort
  ports:
    - port: 9093
      protocol: TCP
      name: webport
      nodePort: 32052
  selector:
    run: alertmanager
