apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      scrape_timeout: 10s
      evaluation_interval: 10s
    rule_files:
      - '/etc/alertmanager/alert.rules'
      - '/etc/prom-record/record.rules'
    scrape_configs:
     # https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml#L156
      - job_name: 'kubernetes-pods'

        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          # - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          #   action: keep
          #   regex: true
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: prom-kafka(.*)|agent
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: (.+):(?:\d+);(\d+)
            replacement: ${1}:${2}
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-configmap-kafka
  namespace: monitoring
