apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      scrape_timeout: 10s
      evaluation_interval: 10s
    rule_files:
      - '/etc/alertmanager/alert.rules'
      - '/etc/prom-record/record.rules'
    scrape_configs:
      - job_name: 'federate'
        scrape_interval: 10s
        honor_labels: true
        metrics_path: '/federate'
        params:
         'match[]':
           - '{__name__=~"job:.*"}'
        static_configs:
         - targets:
           - 'prometheus-server-agent:9090'
           - 'prometheus-server-nodes:9090'
           - 'prometheus-server-endpoints:9090'

      - job_name: 'pushgateway'
        scrape_interval: 10s
        honor_labels: true
        static_configs:
          - targets: ['prometheus-pushgateway.monitoring.svc.cluster.local:9091']

      - job_name: 'mongodb-node'
        static_configs:
          - targets: [{%for h in groups["mongodb"]%} '{{h}}:9100'{% if loop.index != groups['mongodb']|length %},{%endif%} {%endfor%}]
      - job_name: 'kafka-node'
        static_configs:
          - targets: [{%for h in groups["kafka"]%} '{{h}}:9100'{% if loop.index != groups['kafka']|length %},{%endif%} {%endfor%}]
      - job_name: 'redis-node'
        static_configs:
          - targets: [{%for h in groups["redis"]%} '{{h}}:9100'{% if loop.index != groups['redis']|length %},{%endif%} {%endfor%}]
      # https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml#L119
      - job_name: 'kubernetes-services'
        metrics_path: /probe
        params:
          module: [http_2xx]
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe]
            action: keep
            regex: true
          - source_labels: [__address__]
            target_label: __param_target
          - target_label: __address__
            replacement: blackbox
          - source_labels: [__param_target]
            target_label: instance
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_service_name]
            target_label: kubernetes_name

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-configmap-global
  namespace: monitoring
