apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      scrape_timeout: 10s
      evaluation_interval: 10s
    rule_files:
      - '/etc/alertmanager/alert.rules'
      - '/etc/prom-record/record.rules'
    scrape_configs:
      # https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml#L37
      - job_name: 'kubernetes-nodes'
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__address__]
            regex: '(.*):10250'
            replacement: '${1}:10255'
            target_label: __address__
          - source_labels: [__meta_kubernetes_node_label_app]
            target_label: app
          - action: labelmap
            regex: __meta_kubernetes_node_label_res_(.+)
            replacement: 'res'

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-configmap-nodes
  namespace: monitoring
