apiVersion: v1
kind: Service
metadata:
  name: prometheus-server-agent
  namespace: monitoring
  labels:
    app: prometheus-server-agent
    component: core
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: NodePort
  ports:
    - port: 9090
      protocol: TCP
      name: webui
      nodePort: {{prometheus_agent_port}}
  selector:
    app: prometheus-server-agent
    component: core
