apiVersion: v1
kind: Service
metadata:
  name: prometheus-pushgateway
  namespace: monitoring
  labels:
    app: prometheus-pushgateway
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: NodePort
  ports:
    - port: 9091
      protocol: TCP
      name: webui
      nodePort: 32056
  selector:
    app: prometheus-pushgateway
